In [ ]:
import numpy as np
    
# 1. Initialize an empty array with size 2X2
earr = np.empty((2, 2))
print("Empty 2x2 Array:\n", earr)


 Empty 2x2 Array:
 [[0.00000000e+000 1.17209407e-311]
 [1.17209407e-311 1.17209407e-311]]


In [65]:
# 2. Initialize an all one array with size 4X2
oarr = np.ones((4, 2))
print("All Ones 4x2 Array:\n", oarr)
  

All Ones 4x2 Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# 3. Return a new array filled with a specific value
farr = np.full((3, 3), 7)
print("Array filled with 7:\n", farr)
    


 Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
# 4. Return zeros like an existing array
exarr = np.array([[1, 2], [3, 4]])
zearr = np.zeros_like(exarr)
print("Zeros Like Existing Array:\n", zearr)

# 5. Return ones like an existing array
olarray = np.ones_like(exarr)
print("\n Ones Like Existing Array:\n", olarray)


 Zeros Like Existing Array:
 [[0 0]
 [0 0]]

 Ones Like Existing Array:
 [[1 1]
 [1 1]]


In [ ]:
# 6. Convert list to NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("List converted to NumPy Array:\n", numpy_array)


 List converted to NumPy Array:
 [1 2 3 4]


In [3]:
import numpy as np
# 1. Create an array with values ranging from 10 to 49
arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
# 2. Create 3by 3 matrix with values ranging from 0 to 8
mat = np.arange(0,9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
imat=np.eye(3)
print(imat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
rarr=np.random.random(30)
m=rarr.mean()
print("Random array:",rarr)
print("Mean: ",m)

Random array: [0.77494164 0.78849924 0.23527435 0.25919779 0.78203813 0.09743911
 0.12114899 0.08675813 0.42384213 0.67603164 0.51231524 0.91244388
 0.41140068 0.34226968 0.82851705 0.21870929 0.07752911 0.26571131
 0.20108527 0.43102001 0.99289975 0.69854211 0.31108459 0.27267385
 0.01800741 0.8777386  0.39238076 0.22602718 0.30599067 0.18761718]
Mean:  0.42430449268078213


In [14]:
random=np.random.random((10,10))
min=random.min()
max=random.max()
print("10 by 10 random array:",random)
print("Minimum value: ",min)
print("Maximum value",max)

10 by 10 random array: [[0.90072613 0.91235404 0.06829551 0.51635081 0.10136537 0.9122766
  0.37764651 0.60453324 0.86559174 0.42157998]
 [0.54035919 0.67917127 0.19906283 0.15627558 0.78035037 0.15309361
  0.48234695 0.14454861 0.66618202 0.45768142]
 [0.5582346  0.01117942 0.21770475 0.37332004 0.53712033 0.89895922
  0.95786073 0.55833764 0.224181   0.8792615 ]
 [0.10968855 0.75299053 0.91427643 0.81476427 0.46489774 0.47017601
  0.37560412 0.70164282 0.33173405 0.20175398]
 [0.78602663 0.82404418 0.60273746 0.43409773 0.96702343 0.70078163
  0.18843236 0.99712034 0.39993363 0.70819535]
 [0.24127994 0.17947491 0.21808981 0.04490458 0.51192747 0.81404341
  0.28665051 0.26548667 0.86755198 0.88070617]
 [0.30576405 0.50922803 0.01651923 0.39146673 0.90251971 0.08973742
  0.17885584 0.90441579 0.07274878 0.62523278]
 [0.92878192 0.88774294 0.93397133 0.23991075 0.76472931 0.13570571
  0.76328564 0.20684767 0.29035896 0.02591485]
 [0.90542124 0.09954624 0.95055595 0.49995217 0.1865681  0

In [26]:
zarr=np.zeros((10),dtype=int)
zarr[4]=1
print(zarr)

[0 0 0 0 1 0 0 0 0 0]


In [16]:
arr=np.array([1,2,0,0,4,0])
rarr=arr[::-1]
print(rarr)

[0 4 0 0 2 1]


In [25]:
barr=np.ones((5,5),dtype=int)
barr[1:-1,1:-1]=0
print(barr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [24]:
chk=np.zeros((8,8),dtype=int)
chk[1::2,::2]=1
chk[::2,1::2]=1
print(chk)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [27]:
#1 . add two arrays

x=np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
v=np.array([9,10])
w=np.array([11,12])

ares=x+y
print(ares)

[[ 6  8]
 [10 13]]


In [28]:
#2. Subtract the two arrays 
sres=x-y
print(sres)

[[-4 -4]
 [-4 -3]]


In [29]:
#3. Multiply the array with any integers of your choice.
xmul=x*2
ymul=y*4
print(xmul)
print(ymul)

[[ 2  4]
 [ 6 10]]
[[20 24]
 [28 32]]


In [30]:
#4. Find the square of each element of the array.
xsq=np.square(x)
ysq=np.square(y)
print(xsq)
print(ysq)


[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]


In [33]:
#5. Find the dot product between v(and)w ; x(and)v ; x(and)y.
dotvw=np.dot(v,w)
print(dotvw)

dotxv=np.dot(x,v)
print(dotxv)

dotxy=np.dot(x,y)
print(dotxy)

219
[29 77]
[[19 22]
 [50 58]]


In [37]:
#6. COncatenate x and y along row and concatenate v and w along column.
conxy=np.concatenate((x,y), axis=0)
print(conxy)

convw=np.vstack((v,w)).T
print(convw)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


In [ ]:
conxv=np.concatenate((x,v),axis=0)
#x chai 2by2 matrix ho and v chai 1D array of length 2

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
#Problem 4: Matrix Operation

a=np.array([[3,4],[7,8]])
b=np.array([[5,3],[2,1]])

#Prove A.A^-1 = I
invA=np.linalg.inv(a)
idmat=np.dot(a,invA)
print(idmat)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
#Prove AB != BA
ab=np.dot(a,b)
ba=np.dot(b,a)
print("AB: \n",ab)
print("BA: \n",ba)
if np.array_equal(ab,ba):
    print("Equal")
else:
    print("not equal. Hence, proved")

AB: 
 [[23 13]
 [51 29]]
BA: 
 [[36 44]
 [13 16]]
not equal. Hence, proved


In [51]:

abtran=np.transpose(ab)
a_btran=np.dot(b.T,a.T)
print("LHS: \n",abtran)
print("RHS: \n",a_btran)
if np.array_equal(abtran,a_btran):
    print("Equal. Hence, proved")
else:
    print("not equal")

LHS: 
 [[23 51]
 [13 29]]
RHS: 
 [[23 51]
 [13 29]]
Equal. Hence, proved


In [57]:
coeff=np.array([[2,-3,1],[1,-1,2],[3,1,-1]])

cons=np.array([-1,-3,9])

res = np.dot(np.linalg.inv(coeff),cons)# formula A^(-1)*B

print("Solution: \n",res)

Solution: 
 [ 2.  1. -2.]
